### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Sheidus** [SuperLlama88888/holoprint#22]
Because when you imported the mcestructure file And I click on generate, it does not generate the mcpack file. What can I do to solve this problem?

**Comment by SuperLlama88888** [comment]
@Sheidus Could you please attach your `.mcstructure` file here? I'll take a look at it.
Also, what device are you using?

**Comment by Sheidus** [comment]
[granja de pólvora.zip](https://github.com/user-attachments/files/17925712/granja.de.polvora.zip)

@SuperLlama88888 
I'm on an Android Samsung a21s

**Comment by Sheidus** [comment]
Also a few days ago it left me normal, but now I tried and nothing, I tried another device to see if it was this one but the same thing happened.

**Comment by SuperLlama88888** [comment]
It worked for me totally fine, here it is: (rename to .mcpack)
[granja de pólvora.holoprint.zip](https://github.com/user-attachments/files/17925890/granja.de.polvora.holoprint.zip)

I'd still like to understand this issue, were there any logs when you run this?

**Comment by Sheidus** [comment]
[holoprint_logs.json](https://github.com/user-attachments/files/17925986/holoprint_logs.json)

**Comment by SuperLlama88888** [comment]
That's funny, according to the logs it generated the pack without issues.
It should download automatically after generating the pack, and there should be a button to download it if the automatic download doesn't work. I'm going to turn off auto-downloading soon, but the download button should always work.
I'll test this on a similar device soon. Thanks for reporting this issue!

**Comment by Sheidus** [comment]
Sounds good to me, thanks for your help too.

**Comment by NORALDM** [comment]
I have the same problem as well @SuperLlama88888, Firefox console shows the following error:
Uncaught (in promise) TypeError: createSupabaseClient is not a function
    SupabaseLogger https://superllama88888.github.io/holoprint/SupabaseLogger.js:9
    makePack https://superllama88888.github.io/holoprint/index.js:212
    async* https://superllama88888.github.io/holoprint/index.js:100
    EventListener.handleEvent* https://superllama88888.github.io/holoprint/index.js:91
    EventListener.handleEvent* https://superllama88888.github.io/holoprint/index.js:45

**Comment by SuperLlama88888** [comment]
@NORALDM AHHH thank you, I did the big silly. This is just the anonymised statistics reporter, the main functionality should work fine. Will be patched in #23.
