### ISSUE TITLE
Schematic with add-on blocks not displaying

### ISSUE THREAD

**Issue by JORICK404** [SuperLlama88888/holoprint#26]
A schematic that includes blocks from add-ons does not display at all. I’m unsure if there is a method to include custom add-on blocks in the schematic. If such a method exists, I would greatly appreciate a detailed explanation.

**Comment by SuperLlama88888** [comment]
Could you please attach your `.mcstructure` file here so I can take a look at it?

In future, I'll try to add support for custom blocks from addons, but that wouldn't be coming until maybe May next year? Just giving an estimate.

**Comment by JORICK404** [comment]
[21.zip](https://github.com/user-attachments/files/18204472/21.zip)
Could you implement the ability to create holograms without displaying custom blocks? I really want to use your schematic, but I play on a server where there are custom blocks.

**Comment by SuperLlama88888** [comment]
Hmm, I think I know why. I'll try to get a patch out in the next 12 hours. Custom blocks won't render properly, but everything else will.

**Comment by JORICK404** [comment]
I’m very grateful, and I hope that you will implement support for custom blocks in the future.

**Comment by SuperLlama88888** [comment]
@JORICK404 This should be fixed, please let me know if it works now!

**Comment by JORICK404** [comment]
[21.holoprint (3).zip](https://github.com/user-attachments/files/18211364/21.holoprint.3.zip)
No, the hologram does not appear.

**Comment by SuperLlama88888** [comment]
@JORICK404 Sorry for getting back a bit late. Try clearing your history for the Holoprint website then remake the pack, it should work.

**Comment by JORICK404** [comment]
Thank you, everything is working now.
